// dry-typescript fingerprint: 107894fd8bde72acff9786a86384d39b

// Generated by dry-typescript. Do not edit this file directly.
// Source: app/structs/address.rb

export type Address = {
  street: string;
  city: string;
  zip: string | null;
}
