// dry-typescript fingerprint: 1b639ea599a06a04bf6ea39fa3673c0e

// Generated by dry-typescript. Do not edit this file directly.
// Source: app/structs/user.rb

import type { Address } from './Address'

export type User = {
  id: number;
  name: string;
  email: string;
  age: number | null;
  active: boolean;
  address: Address;
  tags: string[];
}
