# frozen_string_literal: true

module Dry
  module TypeScript
    module FileContentBuilder
      include TypeNaming
      include ExportHelpers

      FINGERPRINT_PREFIX = "// dry-typescript fingerprint:"

      def build_file_content(result, filter_imports_to: nil, source_location: nil)
        parts = []
        parts << generated_comment(source_location)
        parts << build_imports(result[:dependencies], filter_to: filter_imports_to)
        parts << result[:typescript]

        parts.reject(&:empty?).join("\n\n") + "\n"
      end

      def generated_comment(source_location)
        lines = ["// Generated by dry-typescript. Do not edit this file directly."]
        lines << "// Source: #{source_location}" if source_location
        lines.join("\n")
      end

      def build_imports(dependencies, filter_to: nil)
        filtered = dependencies.uniq
        filtered = filtered.select { |d| filter_to.include?(d) } if filter_to
        sorted = filtered.sort_by { |d| extract_type_name(d) }

        sorted.map do |dep_class|
          type_name = extract_type_name(dep_class)
          build_import_statement(type_name)
        end.join("\n")
      end

      def build_index_content(structs)
        sorted = structs.sort_by { |s| extract_type_name(s) }
        exports = sorted.map do |struct_class|
          type_name = extract_type_name(struct_class)
          build_index_export(type_name)
        end

        "#{generated_comment(nil)}\n\n#{exports.join("\n")}\n"
      end
    end
  end
end
